// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84u6dYWQ3LpvQYmhxMczMWyHY3t7h4RM',
    appId: '1:813856656513:web:f7d3ed8fe285b3c8d9d180',
    messagingSenderId: '813856656513',
    projectId: 'technostore-v2',
    authDomain: 'technostore-v2.firebaseapp.com',
    storageBucket: 'technostore-v2.firebasestorage.app',
    measurementId: 'G-M39C3GQSJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtsjgIEYqSRM5gwFZCbKrV18jIBo4U5CI',
    appId: '1:813856656513:android:9c35d4a6377f9ef3d9d180',
    messagingSenderId: '813856656513',
    projectId: 'technostore-v2',
    storageBucket: 'technostore-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsdhIGkHZvABXcWswH9eWNrQhprzoVobA',
    appId: '1:813856656513:ios:c462fe83e62d9404d9d180',
    messagingSenderId: '813856656513',
    projectId: 'technostore-v2',
    storageBucket: 'technostore-v2.firebasestorage.app',
    iosBundleId: 'com.Techno.technoStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsdhIGkHZvABXcWswH9eWNrQhprzoVobA',
    appId: '1:813856656513:ios:c462fe83e62d9404d9d180',
    messagingSenderId: '813856656513',
    projectId: 'technostore-v2',
    storageBucket: 'technostore-v2.firebasestorage.app',
    iosBundleId: 'com.Techno.technoStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB84u6dYWQ3LpvQYmhxMczMWyHY3t7h4RM',
    appId: '1:813856656513:web:23494c6a16aa9c1ad9d180',
    messagingSenderId: '813856656513',
    projectId: 'technostore-v2',
    authDomain: 'technostore-v2.firebaseapp.com',
    storageBucket: 'technostore-v2.firebasestorage.app',
    measurementId: 'G-L3QT8CQZ34',
  );
}
