// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA_GxZcUaHBt0s7m-rPAJUeNR14eoE9Aw',
    appId: '1:861642035851:web:99a5cda37012d2189bfa8e',
    messagingSenderId: '861642035851',
    projectId: 'technostore-86118',
    authDomain: 'technostore-86118.firebaseapp.com',
    storageBucket: 'technostore-86118.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIWE5aLXBDbLOJNpJUw5JXwEScAM0NOuc',
    appId: '1:861642035851:android:af2e8ecf86a2b28a9bfa8e',
    messagingSenderId: '861642035851',
    projectId: 'technostore-86118',
    storageBucket: 'technostore-86118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-8Xc7gr0jtw5LzC3pmC6FYiUSxk-s-M',
    appId: '1:861642035851:ios:22f27183ca5dd85a9bfa8e',
    messagingSenderId: '861642035851',
    projectId: 'technostore-86118',
    storageBucket: 'technostore-86118.appspot.com',
    iosBundleId: 'com.Techno.technoStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-8Xc7gr0jtw5LzC3pmC6FYiUSxk-s-M',
    appId: '1:861642035851:ios:22f27183ca5dd85a9bfa8e',
    messagingSenderId: '861642035851',
    projectId: 'technostore-86118',
    storageBucket: 'technostore-86118.appspot.com',
    iosBundleId: 'com.Techno.technoStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA_GxZcUaHBt0s7m-rPAJUeNR14eoE9Aw',
    appId: '1:861642035851:web:163409aaefc008d69bfa8e',
    messagingSenderId: '861642035851',
    projectId: 'technostore-86118',
    authDomain: 'technostore-86118.firebaseapp.com',
    storageBucket: 'technostore-86118.appspot.com',
  );
}
